/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ScreenshotConfig {
  savePath?: string
  format?: string
  quality?: number
  mosaicBlockSize?: number
  defaultColor?: string
  defaultSize?: number
  locale?: string
  showDebugHud?: boolean
  metricsIntervalMs?: number
}
export declare function start(config?: ScreenshotConfig | undefined | null): string
export declare class ScreenshotSession {
  cancel(): void
  pollEvent(): string | null
}
